//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirportDispatcher.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingTickets
    {
        public int IdBookingTicket { get; set; }
        public Nullable<int> IdBooking { get; set; }
        public Nullable<int> IdTicketSelling { get; set; }
    
        public virtual Bookings Bookings { get; set; }
        public virtual TicketsSelling TicketsSelling { get; set; }
    }
}
