//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirportDispatcher.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bookings()
        {
            this.BookingTickets = new HashSet<BookingTickets>();
        }
    
        public int IdBooking { get; set; }
        public string BookingCode { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<int> IdBookingStatus { get; set; }
    
        public virtual BookingsStatus BookingsStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingTickets> BookingTickets { get; set; }
    }
}
