//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirportDispatcher.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int IdRegistration { get; set; }
        public Nullable<int> IdBagage { get; set; }
        public Nullable<int> IdStatusRegistration { get; set; }
        public Nullable<int> IdTicketSelling { get; set; }
    
        public virtual Bagage Bagage { get; set; }
        public virtual StatusRegistration StatusRegistration { get; set; }
        public virtual TicketsSelling TicketsSelling { get; set; }
    }
}
