//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirportDispatcher.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketsSelling
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TicketsSelling()
        {
            this.BookingTickets = new HashSet<BookingTickets>();
            this.Registration = new HashSet<Registration>();
        }
    
        public int IdTicketSelling { get; set; }
        public int IdFlight { get; set; }
        public int NumberTicket { get; set; }
        public string PassportNumber { get; set; }
        public string PlaceOfIssue { get; set; }
        public System.DateTime DateOfIssue { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string Surname { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int BagageCount { get; set; }
        public Nullable<int> FormOfPaymentId { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingTickets> BookingTickets { get; set; }
        public virtual Flights Flights { get; set; }
        public virtual FormOfPayments FormOfPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registration> Registration { get; set; }
    }
}
